# Site settings
title: Joerg Weber Engineering
email: joerg@weber-ib.eu
url: https://github.com/jeromelachaud/freelancer-theme
description: "Engineering and Consulting for your medical device or automotive project."
keywords: "system engineer, hardware engineer, requirements engineer, medical device, automotive, consulting, project management"
skills: "Hardware, Software, System, Requirements, Project Management"
meta_author: Weber Joerg

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3c9bfb #80B3FF
  primary-rgb: "60,155,251," #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jörg Weber
  location: Location
  social: Around the Web
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joerg-weber-ib/
  - title: xing
    url: https://www.xing.com/profile/Joerg_Weber121


# Postal address (add as many lines as necessary)
address:
  - line: Paetzstr. 16
  - line: 04435 Schkeuditz,Germany

# Credits content
credits: 'This is the website of my devolpment and consulting company.</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
